# Generated by Django 2.1.5 on 2019-03-18 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.PositiveIntegerField(editable=False)),
                ('receives', models.BooleanField(default=False)),
                ('counts', models.PositiveIntegerField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, editable=False, null=True)),
                ('grand_total', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rawitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=10)),
                ('rate', models.PositiveIntegerField(blank=True)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='rawitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_transaction.Rawitem'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Supplier'),
        ),
    ]
