# Generated by Django 2.1.5 on 2019-02-16 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_item'),
        ('material_transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rawitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_transaction.Rawitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Supplier')),
            ],
        ),
    ]
