# Generated by Django 2.1.5 on 2019-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
