# Generated by Django 2.1.5 on 2019-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0003_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
