# Generated by Django 2.1.5 on 2019-02-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0004_purchase_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='received',
        ),
    ]
