# Generated by Django 2.1.5 on 2019-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0005_remove_purchase_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receives',
            field=models.BooleanField(default=False),
        ),
    ]
