# Generated by Django 2.1.5 on 2019-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0006_purchase_receives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
