# Generated by Django 2.1.5 on 2019-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0007_auto_20190220_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawitem',
            name='rate',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
