# Generated by Django 2.1.5 on 2019-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_transaction', '0010_auto_20190220_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='counts',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
