# Generated by Django 2.1.5 on 2019-03-05 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=50)),
                ('Select_item', models.CharField(max_length=10)),
                ('Quantity', models.PositiveIntegerField(blank=True)),
                ('Order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Target_date', models.DateTimeField()),
                ('Select_customer', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
