# Generated by Django 2.1.5 on 2019-03-18 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('1', 'Shift1'), ('2', 'Shift2'), ('3', 'Shift3')], max_length=1)),
                ('batch_number', models.PositiveIntegerField()),
                ('total_production', models.PositiveIntegerField()),
                ('pack', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('dispatched_date', models.DateField()),
                ('sgst', models.FloatField(blank=True)),
                ('grand_total', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(blank=True)),
                ('Order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Target_date', models.DateField()),
                ('total', models.PositiveIntegerField(editable=False)),
                ('Select_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Customer')),
                ('Select_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Item')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='Workorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Workorder'),
        ),
        migrations.AddField(
            model_name='production',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Item'),
        ),
    ]
