# Generated by Django 2.1.5 on 2019-03-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='itemcode',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Select_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Select_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Item'),
        ),
    ]
