# Generated by Django 2.1.5 on 2019-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='dispatched_date',
            field=models.DateField(null=True),
        ),
    ]
