# Generated by Django 2.1.5 on 2019-03-06 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_item'),
        ('production', '0002_auto_20190305_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.PositiveIntegerField(blank=True)),
                ('batch_number', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Target_date',
            field=models.DateField(),
        ),
    ]
