# Generated by Django 2.1.5 on 2019-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20190306_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Target_date',
            field=models.DateTimeField(),
        ),
    ]
