# Generated by Django 2.1.5 on 2019-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20190306_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Target_date',
            field=models.DateField(),
        ),
    ]
