# Generated by Django 2.1.5 on 2019-03-06 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_item'),
        ('production', '0005_auto_20190306_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.PositiveIntegerField(blank=True)),
                ('batch_number', models.DateField()),
                ('total_production', models.PositiveIntegerField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='production_date',
            name='item',
        ),
        migrations.DeleteModel(
            name='Production_date',
        ),
    ]
