# Generated by Django 2.1.5 on 2019-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20190306_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='shift',
            field=models.CharField(choices=[('1', 'Shift1'), ('2', 'Shift2'), ('3', 'Shift3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='production',
            name='total_production',
            field=models.PositiveIntegerField(),
        ),
    ]
