# Generated by Django 2.1.5 on 2019-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20190306_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='batch_number',
            field=models.PositiveIntegerField(),
        ),
    ]
