# Generated by Django 2.1.5 on 2019-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_workorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='pack',
            field=models.BooleanField(default=False),
        ),
    ]
