# Generated by Django 2.1.5 on 2019-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_production_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Order_date',
            field=models.DateField(),
        ),
    ]
