# Generated by Django 2.1.5 on 2019-03-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20190309_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='Workorder_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.Workorder'),
            preserve_default=False,
        ),
    ]
