# Generated by Django 2.1.5 on 2019-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_production_workorder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1)),
                ('Quantity', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(editable=False)),
                ('Select_customer', models.CharField(max_length=1)),
            ],
        ),
    ]
