# Generated by Django 2.1.5 on 2019-03-12 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
