# Generated by Django 2.1.5 on 2019-03-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_dispatch_dispatch_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dispatch',
        ),
    ]
