# Generated by Django 2.1.5 on 2019-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_delete_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
