# Generated by Django 2.1.5 on 2019-03-16 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_production_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='dispatched_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
