# Generated by Django 2.1.5 on 2019-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_customer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
